site_name: Nicholas
site_url: https://nicholaslyz.com/

theme:
  name: material
  palette:
    scheme: slate
    primary: indigo
    accent: yellow
  favicon: "static/images/favicon.png"
  logo: "static/images/favicon.png"
  custom_dir: overrides
  features:
    - navigation.instant
    - header.autohide
    - navigation.sections
    - navigation.indexes
    - navigation.expand

extra_css:
  - stylesheets/code.css

nav:
  - Home: index.md
  - About: about.md
  - Blog:
      - blog/index.md
  - Pinned:
      - Mountaineering: mountaineering.md
      - Travel Bucket List: travel-bucket-list.md
      - Photography: photography.md
      - Piano: piano.md
      - Dead Man's Switch: dead-mans-switch.md
      - My Diet: my-diet.md

markdown_extensions:
  - abbr
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - admonition
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true
  - footnotes
  - pymdownx.snippets
  - pymdownx.keys
  - pymdownx.arithmatex:
      generic: true
  - md_in_html

plugins:
  - search
  - social
  - glightbox
  - blog:
      blog_toc: true
      categories_allowed:
        - Cooking
        - Finance
        - Insurance
        - Philosophy
        - Programming
        - Outdoor
        - Debates
      post_excerpt: required
      archive: false
  - redirects:
      redirect_maps:
        "blog-posts/2020-09-21-finance-book-list.md": blog/posts/2020-09-21-finance-book-list.md
        "blog-posts/2020-09-21-iem-reviews.md": blog/posts/2020-09-21-iem-reviews.md
        "blog-posts/2020-09-24-cloudflare-and-github-pages.md": blog/posts/2020-09-24-cloudflare-and-github-pages.md
        "blog-posts/2020-11-28-making-stevia-powder.md": blog/posts/2020-11-28-making-stevia-powder.md
        "blog-posts/2020-11-30-getting-started-with-investing.md": blog/posts/2020-11-30-getting-started-with-investing.md
        "blog-posts/2020-12-02-asset-allocation.md": blog/posts/2020-12-02-asset-allocation.md
        "blog-posts/2021-01-16-my-investment-portfolio.md": blog/posts/2021-01-16-my-investment-portfolio.md
        "blog-posts/2021-03-19-life-insurance.md": blog/posts/2021-03-19-life-insurance.md
        "blog-posts/2021-04-15-python-package-management-windows.md": blog/posts/2021-04-15-python-package-management-windows.md
        "blog-posts/2021-04-22-calculating-return.md": blog/posts/2021-04-22-calculating-return.md
        "blog-posts/2021-06-08-which-is-the-best-index-fund-etf.md": blog/posts/2021-06-08-which-is-the-best-index-fund-etf.md
        "blog-posts/2021-06-18-ge-totalcare-comparison.md": blog/posts/2021-06-18-ge-totalcare-comparison.md
        "blog-posts/2021-06-19-comparison-of-isp-riders.md": blog/posts/2021-06-19-comparison-of-isp-riders.md
        "blog-posts/2021-06-20-uselayouteffect.md": blog/posts/2021-06-20-uselayouteffect.md
        "blog-posts/2021-07-23-cracking-pdf-hashes.md": blog/posts/2021-07-23-cracking-pdf-hashes.md
        "blog-posts/2021-07-25-endowus-or-not.md": blog/posts/2021-07-25-endowus-or-not.md
        "blog-posts/2021-07-25-my-endowus-portfolio.md": blog/posts/2021-07-25-my-endowus-portfolio.md
        "blog-posts/2021-09-16-crispy-pork-belly.md": blog/posts/2021-09-16-crispy-pork-belly.md
        "blog-posts/2021-11-17-developing-in-wsl-containers.md": blog/posts/2021-11-17-developing-in-wsl-containers.md
        "blog-posts/2021-12-04-apple-chips-recipe.md": blog/posts/2021-12-04-apple-chips-recipe.md
        "blog-posts/2021-12-17-useful-utilities.md": blog/posts/2021-12-17-useful-utilities.md
        "blog-posts/2021-12-25-skiing-switzerland.md": blog/posts/2021-12-25-skiing-switzerland.md
        "blog-posts/2021-12-30-npm-update-behavior.md": blog/posts/2021-12-30-npm-update-behavior.md
        "blog-posts/2022-02-04-deep-work.md": blog/posts/2022-02-04-deep-work.md
        "blog-posts/2022-02-07-ssh-with-certificates.md": blog/posts/2022-02-07-ssh-with-certificates.md
        "blog-posts/2022-02-07-vscode-remote-containers-over-ssh.md": blog/posts/2022-02-07-vscode-remote-containers-over-ssh.md
        "blog-posts/2022-02-26-fedora-win11-dual-boot.md": blog/posts/2022-02-26-fedora-win11-dual-boot.md
        "blog-posts/2022-02-27-my-computing-philosophy.md": blog/posts/2022-02-27-my-computing-philosophy.md
        "blog-posts/2022-03-03-determinism-and-stoicism.md": blog/posts/2022-03-03-determinism-and-stoicism.md
        "blog-posts/2022-03-05-on-happiness.md": blog/posts/2022-03-05-on-happiness.md
        "blog-posts/2022-03-24-best-practices-debugging-service-workers.md": blog/posts/2022-03-24-best-practices-debugging-service-workers.md
        "blog-posts/2022-03-30-artificial-intelligence-language-models.md": blog/posts/2022-03-30-artificial-intelligence-language-models.md
        "blog-posts/2022-05-21-note-taking.md": blog/posts/2022-05-21-note-taking.md
        "blog-posts/2022-05-22-my-self-hosting-journey.md": blog/posts/2022-05-22-my-self-hosting-journey.md
        "blog-posts/2022-07-10-docker-gpu-fedora.md": blog/posts/2022-07-10-docker-gpu-fedora.md
        "blog-posts/2022-07-10-win11-vm-gpu-passthrough.md": blog/posts/2022-07-10-win11-vm-gpu-passthrough.md
        "blog-posts/2022-07-18-android-vm-browser.md": blog/posts/2022-07-18-android-vm-browser.md
        "blog-posts/2022-08-01-my-diet.md": my-diet.md
        "blog-posts/2022-08-05-vipassana-meditation-retreat.md": blog/posts/2022-08-05-vipassana-meditation-retreat.md
        "blog-posts/2022-08-11-is-this-world-real.md": blog/posts/2022-08-11-is-this-world-real.md
        "blog-posts/2022-10-28-nutrition-and-health.md": blog/posts/2022-10-28-nutrition-and-health.md
        "blog-posts/2022-11-26-photoprism-google-photos.md": blog/posts/2022-11-26-photoprism-google-photos.md
        "blog-posts/2022-12-16-japan-tomamu-skiing.md": blog/posts/2022-12-16-japan-tomamu-skiing.md
        "blog-posts/2022-12-27-on-the-measure-of-intelligence.md": blog/posts/2022-12-27-on-the-measure-of-intelligence.md
        "blog-posts/2023-01-11-self-hosted-vpn.md": blog/posts/2023-01-11-self-hosted-vpn.md
        "blog-posts/2023-02-01-music-management.md": blog/posts/2023-02-01-music-management.md
        "blog-posts/2023-06-24-mikrotik-singtel-setup.md": blog/posts/2023-06-24-mikrotik-singtel-setup.md
        "blog-posts/2023-07-10-camping-gear.md": blog/posts/2023-07-10-camping-gear.md
        "blog-posts/2023-07-19-attractiveness.md": blog/posts/2023-07-19-attractiveness.md
        "blog-posts/2023-08-30-video-archiving-ffmpeg.md": blog/posts/2023-08-30-video-archiving-ffmpeg.md
        "blog-posts/2023-09-11-best-way-cook-beans.md": blog/posts/2023-09-11-best-way-cook-beans.md
        "blog-posts/2023-09-17-yjs-vs-databases.md": blog/posts/2023-09-17-yjs-vs-databases.md

extra:
  analytics:
    provider: google
    property: G-22SGZWR3ES
  social:
    - icon: material/github
      link: https://github.com/extrange/
    - icon: material/email
      link: mailto:me@nicholaslyz.com

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
