site_name: Nicholas
site_url: https://nicholaslyz.com/

theme:
  name: material
  palette:
    scheme: slate
    primary: indigo
    accent: yellow
  favicon: 'static/images/favicon.png'
  logo: 'static/images/favicon.png'
  custom_dir: overrides
  features:
    - navigation.instant
    - header.autohide
    - navigation.sections
    - navigation.indexes
    - navigation.expand
  
extra_css:
  - stylesheets/code.css

nav:
  - Home: index.md
  - About Me: about.md
  - Blog:
      - blog/index.md
  - Dead Man's Switch: dead-mans-switch.md
  - Mountaineering: mountaineering.md
  - Travel Bucket List: travel-bucket-list.md
  - Photography: photography.md
  - Piano: piano.md
  - Resume: resume.md
  
markdown_extensions:
  - abbr
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true
  - footnotes
  - pymdownx.snippets
  - pymdownx.keys
  - pymdownx.arithmatex:
      generic: true

plugins:
  - search
  - social
  - glightbox
  - blog:
      blog_toc: true
      categories_allowed:
        - Cooking
        - Finance
        - Insurance
        - Philosophy
        - Programming
      post_excerpt: required

extra:
  analytics:
    provider: google
    property: G-22SGZWR3ES
  social:
    - icon: material/github
      link: https://github.com/extrange/
    - icon: material/email
      link: mailto:me@nicholaslyz.com

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js