site_name: Nicholas
site_url: https://nicholaslyz.com/

theme:
  name: material
  palette:
    scheme: slate
    primary: indigo
    accent: yellow
  favicon: "static/images/favicon.png"
  logo: "static/images/favicon.png"
  custom_dir: overrides
  features:
    - navigation.instant
    - header.autohide
    - navigation.sections
    - navigation.indexes
    - navigation.expand
    - content.code.copy

nav:
  - Home: index.md
  - About: about.md
  - Blog:
      - blog/index.md
  - Pinned:
      - Dead Man's Switch: dead-mans-switch.md
      - Lifestyle:
          - principles.md
          - daily-routine.md
      - Mountaineering: mountaineering.md
      - Photography: photography.md
      - Piano: piano.md
      - Travel Bucket List: travel-bucket-list.md

markdown_extensions:
  - abbr
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - admonition
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true
  - footnotes
  - pymdownx.snippets
  - pymdownx.keys
  - pymdownx.arithmatex:
      generic: true
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true

plugins:
  - search
  - social
  - glightbox
  - blog:
      blog_toc: true
      categories_allowed:
        - Books
        - Cooking
        - Finance
        - Insurance
        - Philosophy
        - Programming
        - Outdoor
        - Debates
      post_excerpt: required
      archive: false

extra:
  social:
    - icon: material/github
      link: https://github.com/extrange/
    - icon: material/email
      link: mailto:me@nicholaslyz.com

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - stylesheets/code.css
