site_name: Nicholas
theme:
  name: material
  palette:
    scheme: slate
    primary: cyan
    accent: yellow
  favicon: '/static/images/favicon.png'
  icon:
    logo: material/home
  features:
    - navigation.instant
    - header.autohide
site_url: https://nicholaslyz.com/
nav:
  - Home: index.md
  - About Me: about.md
  - Blog Posts:
    - VSCode Remote Containers over SSH: blog-posts/2022-02-07-vscode-remote-containers-over-ssh.md
    - SSH with Certificates: 'blog-posts/2022-02-07-ssh-with-certificates.md'
    - Deep Work: 'blog-posts/2022-02-04-deep-work.md'
    - npm update Behavior: 'blog-posts/2021-12-30-npm-update-behavior.md'
    - 'Skiing at St Moritz, Switzerland': 'blog-posts/2021-12-25-skiing-switzerland.md'
    - Useful Utilities: 'blog-posts/2021-12-17-useful-utilities.md'
    - Apple Chips Recipe: 'blog-posts/2021-12-04-apple-chips-recipe.md'
    - Developing in WSL Containers: 'blog-posts/2021-11-17-developing-in-wsl-containers.md'
    - Crispy Pork Belly Recipe: 'blog-posts/2021-09-16-crispy-pork-belly.md'
    - My Endowus Portfolio: 'blog-posts/2021-07-25-my-endowus-portfolio.md'
    - To Endowus, Or Not?: 'blog-posts/2021-07-25-endowus-or-not.md'
    - Cracking PDF Hashes with hashcat: 'blog-posts/2021-07-23-cracking-pdf-hashes.md'
    - useLayoutEffect: 'blog-posts/2021-06-20-uselayouteffect.md'
    - The Best Index Fund: 'blog-posts/2021-06-08-which-is-the-best-index-fund-etf.md'
    - Calculating Return: 'blog-posts/2020-04-22-calculating-return.md'
    - Python Package Management on Windows: 'blog-posts/2021-04-15-python-package-management-windows.md'
    - Life Insurance: 'blog-posts/2021-03-19-life-insurance.md'
    - My Investment Portfolio: 'blog-posts/2021-01-16-my-investment-portfolio.md'
    - Asset Allocation: 'blog-posts/2020-12-02-asset-allocation.md'
    - Getting Started with Investing: 'blog-posts/2020-11-30-getting-started-with-investing.md'
    - Making Stevia Powder: 'blog-posts/2020-11-28-making-stevia-powder.md'
    - Cloudflare and Github Pages: 'blog-posts/2020-09-24-cloudflare-and-github-pages.md'
    - Finance Booklist: 'blog-posts/2020-09-21-finance-book-list.md'
    - IEM Reviews: 'blog-posts/2020-09-21-iem-reviews.md'
  - Dead Man's Switch: dead-mans-switch.md
  - Mountaineering: mountaineering.md
  - Photography: photography.md
  - Piano: piano.md
  - Resume: resume.md
markdown_extensions:
  - abbr
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true
  - footnotes
  - pymdownx.snippets
extra:
  analytics:
    provider: google
    property: G-22SGZWR3ES