FROM mcr.microsoft.com/devcontainers/python:1-3.11-bullseye

# [Optional] Uncomment this section to install additional OS packages.
RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
    && apt-get -y install --no-install-recommends cairosvg python3-dev libffi-dev
