name: Bump dependencies
on:
  workflow_dispatch:
  schedule:
    # Run weekly at 00:00 on Sunday
    - cron: "0 0 * * 0"

jobs:
  bump-dependencies:
    runs-on: ubuntu-latest
    outputs:
      has_update: ${{ steps.auto-commit-action.outputs.changes_detected }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Set up pdm
        run: |
          curl -sSL https://pdm-project.org/install-pdm.py | python3 -

      - name: Update dependencies
        run: pdm update -u

      - name: Commit changes
        id: auto-commit-action
        uses: stefanzweifel/git-auto-commit-action@v5

        with:
          commit_message: "Update dependencies"

  deploy:
    needs: bump-dependencies
    if: needs.bump-dependencies.outputs.has_update == 'true'
    uses: ./.github/workflows/deploy.yaml
